Add documentation for rate limiting rules
ONSdigital/dp-developer-site pull request #43
Opened 2021-02-15 13:32 UTC by HeJones

### What

- Add documentation to the developer site. to explain the rate limiting rules that have been applied to the API

### How to review

- Check that there are no typos and that the documentation reads well and is clear. 

### Who can review

Anyone

2021-02-15 14:00 UTC, sandypadmanabhan commented on static/index.md
> +The following rate limiting rules have been implemented on the API
Few lines to explain why we are adding the rate limit would be good. something along the lines of "We limit the number of requests you can make to dp API's to protect our service against excessive use and denial of service attacks ."

2021-02-15 14:00 UTC, sandypadmanabhan commented on static/index.md
> +The following rate limiting rules have been implemented on the API
We also need to mention about the  429 response when we exceed the limit stated and about the Retry-header as mentioned in the trello ticket

2021-02-15 14:00 UTC, sandypadmanabhan commented on static/index.md
> +The following rate limiting rules have been implemented on the API
And can you mention both the domains as well

2021-02-16 09:30 UTC, sandypadmanabhan commented on static/index.md
> +If requests are made that reach these limits the IP address of the client will be blocked for 1 minute. The client will receive a 429 response, the retry-header contains the seconds remaining until a
the retry-header `shows` or something similar would make sense . `retry-header contains the seconds' seems out of place .

2021-02-16 12:36 UTC, gedge requested changes

2021-02-16 12:36 UTC, gedge commented on static/index.md
> +The following rate limiting rules have been implemented on the API.
```suggestion
The following rate limits have been implemented on the API:
```

2021-02-16 12:36 UTC, gedge commented on static/index.md
> +They have been applied to following domains.
```suggestion
They have been applied to following domains:
```

2021-02-16 12:36 UTC, gedge commented on static/index.md
> +Rate limiting rules have been implemented to limit the number of requests a client can make to The Office for National Statistics API. This is to protect the service against excessive use and denial
```suggestion
Rate limiting has been implemented to contain the number of requests a client can make to our API. This is to protect the service against excessive use and denial of service attacks. 
```

1. repeated 'limit' was repetitive 😄 
2. removing 'rules' sounds more direct

2021-02-16 13:37 UTC, sandypadmanabhan commented on static/index.md
> +If requests are made that reach these limits the IP address of the client will be blocked for 1 minute. The client will receive a JSON response with a 429 error code, the retry-after header shows the
The client will receive a JSON response with a 429 error code. The Retry-After header shows the seconds remaining until a retry can be made.

2021-02-16 13:41 UTC, sandypadmanabhan commented on static/index.md
> +### Rate Limiting Rules
Looking at other subheading , this should be `Rate limiting rules`. L and R (lowercase)

2021-02-16 14:44 UTC, sandypadmanabhan approved these changes

2021-02-16 14:59 UTC, gedge approved these changes

2021-02-16 16:46 UTC, merged